//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Smart.Platform.Globalization.Countries.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CountriesData {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CountriesData() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Smart.Platform.Globalization.Countries.Resources.CountriesData", typeof(CountriesData).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Countries&gt;
        ///
        ///    &lt;Country code=&quot;AF&quot;&gt;Afghanistan&lt;/Country&gt;
        ///
        ///    &lt;Country code=&quot;AL&quot;&gt;Albania&lt;/Country&gt;
        ///
        ///    &lt;Country code=&quot;DZ&quot;&gt;Algeria&lt;/Country&gt;
        ///
        ///    &lt;Country code=&quot;AS&quot;&gt;American Samoa&lt;/Country&gt;
        ///
        ///    &lt;Country code=&quot;AD&quot;&gt;Andorra&lt;/Country&gt;
        ///
        ///    &lt;Country code=&quot;AO&quot;&gt;Angola&lt;/Country&gt;
        ///
        ///    &lt;Country code=&quot;AI&quot;&gt;Anguilla&lt;/Country&gt;
        ///
        ///    &lt;Country code=&quot;AQ&quot;&gt;Antarctica&lt;/Country&gt;
        ///
        ///    &lt;Country code=&quot;AG&quot;&gt;Antigua And Barbuda&lt;/Country&gt;
        ///
        ///    &lt;Country code=&quot;AR&quot;&gt;Argentina&lt;/Country&gt;
        ///
        ///    &lt;Country code=&quot;AM&quot;&gt;Armeni [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Xml {
            get {
                return ResourceManager.GetString("Xml", resourceCulture);
            }
        }
    }
}
